<html>
<head>
	<title>{$maintitle}</title>
			<link rel="stylesheet" href="{$subdir}media/stylesheet.css" />
			<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'/>
</head>
<body>
<div align="center"><h1>{$maintitle}</h1></div>
<b>Welcome to the feindura API reference!</b><br />
<br />
This reference was generated out of the comments of the feindura code.
It should provide a sufficient description of all necessary methods and functions used by feindura.<br />
<br />
To implement feindura take a look in the <a href="li_[Implementation].html" target="left_bottom">[Implementation]</a> package, 
there you find the <i>feindura class</i> which should provide every necessary method to implement feindura in your website.<br />
<br />
For more advanced usage see also the <a href="li_[Implementation]-[backend].html" target="left_bottom">[Implementation]-[backend]</a> package. 
<br />
If you want to improve feindura, the <a href="li_[backend].html" target="left_bottom">[backend]</a> and <a href="li_[Implementation]-[backend].html" target="left_bottom">[Implementation]-[backend]</a> package 
should be interesting for you.
<br />
<br />
<hr />
<div class="footer">This documentation was generated by <a href="{$phpdocwebsite}">phpDocumentor v{$phpdocversion}</a></div>
</body>
</html>