<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//FR"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<!-- Generated by phpDocumentor on {$date}  -->
  <title>{$title}</title>
  <meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'/>
  
  {literal}
  <script language="JavaScript">
  /* <![CDATA[ */    
    var framesetLoaded = true;
    
    function loadPage() {
      if(self.location.search.length > 0) {
        // get the url from the [implementation]/...
        var new_url = self.location.href;
        new_url = new_url.substring(new_url.lastIndexOf('%5B'));
        var current_package = new_url.substring(new_url.lastIndexOf('%5B'),new_url.lastIndexOf('%5D'));
        current_package = 'li_['+current_package.substring(3)+'].html';
        //alert(current_package);
        if(document.images) {
          self.right.location.replace(new_url);
          self.left_bottom.location.replace(current_package);
          self.left_top.location.replace('packages.html?'+current_package);
        } else {
          self.right.location.href = new_url;
          self.left_bottom.location.href = current_package;
          self.left_top.location.href = 'packages.html?'+current_package;
        }

      }
    }

  /* ]]> */
  </script>
  {/literal}
</head>

<frameset rows='123,*' border="0" onLoad="loadPage(); return true;"><!-- onLoad="loadPage(); return true;" -->
	<frame src='packages.html' name='left_top' frameborder="0">
	<frameset cols='251,*'>
		<frame src='{$start}' name='left_bottom' frameborder="0">
		<frame src='{$blank}.html' name='right' frameborder="0">
	</frameset>
	<noframes>
		<h2>Frame Error</h2>
		<p>This document is designed to be viewed using frames.
		If you see this message, you are using a non-frame-capable web client.</p>
	</noframes>
</frameset>

</html>